# Generated by Django 2.2.3 on 2019-07-05 09:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iati',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iati_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='IATI UUID')),
                ('activity_identifier', models.CharField(max_length=100, verbose_name='IATI Activity Identifier')),
                ('ready_for_reporting', models.BooleanField(default=0, verbose_name='Ready for IATI reporting?')),
                ('create_date', models.DateTimeField(editable=False, null=True, verbose_name='Create Date')),
                ('modified_date', models.DateTimeField(editable=False, null=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name_plural': 'IATI',
                'ordering': ('activity_identifier',),
            },
        ),
        migrations.CreateModel(
            name='IatiAidType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iati_aid_type_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='IATI Aid Type UUID')),
                ('aid_type', models.CharField(max_length=100, verbose_name='IATI Aid Type')),
                ('code', models.CharField(max_length=25, verbose_name='IATI Aid Type Code')),
                ('create_date', models.DateTimeField(editable=False, null=True, verbose_name='Create Date')),
                ('modified_date', models.DateTimeField(editable=False, null=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name_plural': 'IATI Aid Types',
                'ordering': ('aid_type',),
            },
        ),
        migrations.CreateModel(
            name='IatiCollaborationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iati_collaboration_type_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='IATI Collaboration Type UUID')),
                ('collaboration_type', models.CharField(max_length=100, verbose_name='IATI Collaboration Type')),
                ('code', models.CharField(max_length=25, verbose_name='IATI Collaboration Type Code')),
                ('create_date', models.DateTimeField(editable=False, null=True, verbose_name='Create Date')),
                ('modified_date', models.DateTimeField(editable=False, null=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name_plural': 'IATI Collaboration Types',
                'ordering': ('collaboration_type',),
            },
        ),
        migrations.CreateModel(
            name='IatiCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iati_finance_type_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='IATI Condition UUID')),
                ('condition', models.CharField(blank=True, help_text='Specify terms and conditions attached to the activity that, if not met,may influence the delivery of commitments made by participating organizations.', max_length=100, verbose_name='IATI Condition')),
                ('condition_type', models.CharField(max_length=100, verbose_name='IATI Condition Type')),
                ('code', models.CharField(max_length=25, verbose_name='IATI Condition Type Code')),
                ('condition_attached', models.BooleanField(default=0, verbose_name='IATI Condition Attached?')),
                ('create_date', models.DateTimeField(editable=False, null=True, verbose_name='Create Date')),
                ('modified_date', models.DateTimeField(editable=False, null=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name_plural': 'IATI Condition Types',
                'ordering': ('condition',),
            },
        ),
        migrations.CreateModel(
            name='IatiFinanceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iati_finance_type_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='IATI Finance Type UUID')),
                ('finance_type', models.CharField(max_length=100, verbose_name='IATI Finance Type')),
                ('code', models.CharField(max_length=25, verbose_name='IATI Finance Type Code')),
                ('create_date', models.DateTimeField(editable=False, null=True, verbose_name='Create Date')),
                ('modified_date', models.DateTimeField(editable=False, null=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name_plural': 'IATI Finance Types',
                'ordering': ('finance_type',),
            },
        ),
        migrations.CreateModel(
            name='IatiFlowType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iati_flow_type_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='IATI Flow Type UUID')),
                ('flow_type', models.CharField(max_length=100, verbose_name='IATI Flow Type')),
                ('code', models.CharField(max_length=25, verbose_name='IATI Flow Type Code')),
                ('create_date', models.DateTimeField(editable=False, null=True, verbose_name='Create Date')),
                ('modified_date', models.DateTimeField(editable=False, null=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name_plural': 'IATI Flow Types',
                'ordering': ('flow_type',),
            },
        ),
        migrations.CreateModel(
            name='IatiHumanitarianScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iati_humanitarian_scope_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='IATI Humanitarian Scope UUID')),
                ('humanitarian_scope', models.CharField(max_length=100, verbose_name='IATI Humanitarian Scope')),
                ('code', models.CharField(max_length=25, verbose_name='IATI Humanitarian Scope Code')),
                ('create_date', models.DateTimeField(editable=False, null=True, verbose_name='Create Date')),
                ('modified_date', models.DateTimeField(editable=False, null=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name_plural': 'IATI Humanitarian Scope',
                'ordering': ('humanitarian_scope',),
            },
        ),
        migrations.CreateModel(
            name='IatiProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iati_project_status_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='IATI Project Status UUID')),
                ('project_status', models.CharField(max_length=100, verbose_name='IATI Project Status')),
                ('code', models.CharField(max_length=25, verbose_name='IATI Project Status Code')),
                ('create_date', models.DateTimeField(editable=False, null=True, verbose_name='Create Date')),
                ('modified_date', models.DateTimeField(editable=False, null=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name_plural': 'IATI Project Status',
                'ordering': ('project_status',),
            },
        ),
        migrations.CreateModel(
            name='IatiTiedStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iati_tied_status_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='IATI Tied Status UUID')),
                ('tied_status', models.CharField(max_length=100, verbose_name='IATI Tied Status')),
                ('code', models.CharField(max_length=25, verbose_name='IATI Tied Status Code')),
                ('create_date', models.DateTimeField(editable=False, null=True, verbose_name='Create Date')),
                ('modified_date', models.DateTimeField(editable=False, null=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name_plural': 'IATI Tied Status',
                'ordering': ('tied_status',),
            },
        ),
    ]
