# Generated by Django 2.2.3 on 2019-07-05 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('externalconfigs', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iatitiedstatus',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tied_status_created_by', to='workflow.ActivityUser', verbose_name='Created Vy'),
        ),
        migrations.AddField(
            model_name='iatitiedstatus',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tied_status_modified_by', to='workflow.ActivityUser', verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='iatiprojectstatus',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_status_created_by', to='workflow.ActivityUser', verbose_name='Created Vy'),
        ),
        migrations.AddField(
            model_name='iatiprojectstatus',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_status_modified_by', to='workflow.ActivityUser', verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='iatihumanitarianscope',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='humanitarian_created_by', to='workflow.ActivityUser', verbose_name='Created Vy'),
        ),
        migrations.AddField(
            model_name='iatihumanitarianscope',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='humanitarian_modified_by', to='workflow.ActivityUser', verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='iatiflowtype',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_type_created_by', to='workflow.ActivityUser', verbose_name='Created Vy'),
        ),
        migrations.AddField(
            model_name='iatiflowtype',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_type_modified_by', to='workflow.ActivityUser', verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='iatifinancetype',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_type_created_by', to='workflow.ActivityUser', verbose_name='Created Vy'),
        ),
        migrations.AddField(
            model_name='iatifinancetype',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_type_modified_by', to='workflow.ActivityUser', verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='iaticondition',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condition_type_created_by', to='workflow.ActivityUser', verbose_name='Created Vy'),
        ),
        migrations.AddField(
            model_name='iaticondition',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condition_type_modified_by', to='workflow.ActivityUser', verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='iaticollaborationtype',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaboration_type_created_by', to='workflow.ActivityUser', verbose_name='Created Vy'),
        ),
        migrations.AddField(
            model_name='iaticollaborationtype',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaboration_type_modified_by', to='workflow.ActivityUser', verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='iatiaidtype',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aid_type_created_by', to='workflow.ActivityUser', verbose_name='Created Vy'),
        ),
        migrations.AddField(
            model_name='iatiaidtype',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aid_type_modified_by', to='workflow.ActivityUser', verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='iati',
            name='aid_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='externalconfigs.IatiAidType', verbose_name='IATI Aid Type'),
        ),
        migrations.AddField(
            model_name='iati',
            name='collaboration_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='externalconfigs.IatiCollaborationType', verbose_name='IATI Collaboration Type'),
        ),
        migrations.AddField(
            model_name='iati',
            name='condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='externalconfigs.IatiCondition', verbose_name='IATI Condition'),
        ),
        migrations.AddField(
            model_name='iati',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iati_created_by', to='workflow.ActivityUser', verbose_name='Created Vy'),
        ),
        migrations.AddField(
            model_name='iati',
            name='finance_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='externalconfigs.IatiFinanceType', verbose_name='IATI Finance Type'),
        ),
        migrations.AddField(
            model_name='iati',
            name='flow_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='externalconfigs.IatiFlowType', verbose_name='IATI Flow Type'),
        ),
        migrations.AddField(
            model_name='iati',
            name='humanitarian_scope',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='externalconfigs.IatiHumanitarianScope', verbose_name='IATI Humanitarian Scope'),
        ),
        migrations.AddField(
            model_name='iati',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iati_modified_by', to='workflow.ActivityUser', verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='iati',
            name='project_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='externalconfigs.IatiProjectStatus', verbose_name='IATI Project Status'),
        ),
        migrations.AddField(
            model_name='iati',
            name='tied_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='externalconfigs.IatiTiedStatus', verbose_name='IATI Tied Status'),
        ),
    ]
