# Generated by Django 2.2.3 on 2019-07-05 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicators', '0001_initial'),
        ('workflow', '0001_initial'),
        ('activity', '0002_auto_20190705_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingperiod',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_created_by', to='workflow.ActivityUser', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='reportingperiod',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_modified_by', to='workflow.ActivityUser', verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='objective',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.Country'),
        ),
        migrations.AddField(
            model_name='objective',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.Organization'),
        ),
        migrations.AddField(
            model_name='objective',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='indicators.Objective'),
        ),
        migrations.AddField(
            model_name='indicatortype',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_type_created_by', to='workflow.ActivityUser', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='indicatortype',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_type_modified_by', to='workflow.ActivityUser', verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='indicatortag',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_created_by', to='workflow.ActivityUser', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='indicatortag',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_modified_by', to='workflow.ActivityUser', verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='indicatorresult',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_created_by', to='workflow.ActivityUser', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='indicatorresult',
            name='disaggregation_value',
            field=models.ManyToManyField(blank=True, related_name='disaggregation_values', to='indicators.DisaggregationValue', verbose_name='Disaggregation Values'),
        ),
        migrations.AddField(
            model_name='indicatorresult',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.Indicator', verbose_name='Indicator'),
        ),
        migrations.AddField(
            model_name='indicatorresult',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_modified_by', to='workflow.ActivityUser', verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='indicatorresult',
            name='reporting_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.ReportingPeriod', verbose_name='Reporting Period'),
        ),
        migrations.AddField(
            model_name='indicatorresult',
            name='workflow_level1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.WorkflowLevel1', verbose_name='Related WorkflowLevel1'),
        ),
        migrations.AddField(
            model_name='indicatorresult',
            name='workflow_level2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.WorkflowLevel2', verbose_name='Related WorkflowLevel1'),
        ),
        migrations.AddField(
            model_name='indicatorlibrary',
            name='additional_fields',
            field=models.ManyToManyField(related_name='lib_additional_fields', to='indicators.AdditionalField', verbose_name='Additional Fields'),
        ),
        migrations.AddField(
            model_name='indicatorlibrary',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Approval', verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='indicatorlibrary',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_lib_created_by', to='workflow.ActivityUser', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='indicatorlibrary',
            name='disaggregation',
            field=models.ManyToManyField(to='indicators.DisaggregationValue'),
        ),
        migrations.AddField(
            model_name='indicatorlibrary',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.IndicatorLevel', verbose_name='Indicator IndicatorLevel'),
        ),
        migrations.AddField(
            model_name='indicatorlibrary',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_lib_modified_by', to='workflow.ActivityUser', verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='indicatorlibrary',
            name='objective',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.Objective', verbose_name='WorkflowLevel1 Objective'),
        ),
        migrations.AddField(
            model_name='indicatorlibrary',
            name='periodic_targets',
            field=models.ManyToManyField(related_name='indicator_targets', to='indicators.ReportingPeriod', verbose_name='Periodic Target'),
        ),
        migrations.AddField(
            model_name='indicatorlibrary',
            name='responsible_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.Contact', verbose_name='Responsible Person(s) and Team'),
        ),
        migrations.AddField(
            model_name='indicatorlibrary',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.Sector', verbose_name='Indicator Sector'),
        ),
        migrations.AddField(
            model_name='indicatorlibrary',
            name='tags',
            field=models.ManyToManyField(related_name='indicator_lib_tags', to='indicators.IndicatorTag', verbose_name='Indicator Tags'),
        ),
        migrations.AddField(
            model_name='indicatorlibrary',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.IndicatorType', verbose_name='Indicator Type'),
        ),
        migrations.AddField(
            model_name='indicatorlibrary',
            name='workflow_level1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.WorkflowLevel1', verbose_name='Workflow Level1'),
        ),
        migrations.AddField(
            model_name='indicatorlevel',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_level_created_by', to='workflow.ActivityUser', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='indicatorlevel',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_level_modified_by', to='workflow.ActivityUser', verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='additional_fields',
            field=models.ManyToManyField(related_name='indiactor_additional_fields', to='indicators.AdditionalField', verbose_name='Additional Fields'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Approval', verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_created_by', to='workflow.ActivityUser', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='disaggregation',
            field=models.ManyToManyField(to='indicators.DisaggregationType'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.IndicatorLevel', verbose_name='Indicator IndicatorLevel'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_modified_by', to='workflow.ActivityUser', verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='objective',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.Objective', verbose_name='WorkflowLevel1 Objective'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='periodic_targets',
            field=models.ManyToManyField(related_name='indicator_periodic_target', to='indicators.ReportingPeriod', verbose_name='Periodic Target'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='responsible_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.Contact', verbose_name='Responsible Person(s) and Team'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.Sector', verbose_name='Indicator Sector'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='tags',
            field=models.ManyToManyField(related_name='indicator_tags', to='indicators.IndicatorTag', verbose_name='Indicator Tags'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='target_frequency',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.ReportingPeriod', verbose_name='Target Frequencies'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.IndicatorType', verbose_name='Indicator Type'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='workflow_level1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.WorkflowLevel1', verbose_name='Workflow Level1'),
        ),
        migrations.AddField(
            model_name='externalservicerecord',
            name='external_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.ExternalService'),
        ),
        migrations.AddField(
            model_name='disaggregationvalue',
            name='disaggregation_label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.DisaggregationLabel'),
        ),
        migrations.AddField(
            model_name='disaggregationtype',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.Country'),
        ),
        migrations.AddField(
            model_name='disaggregationlabel',
            name='disaggregation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.DisaggregationType'),
        ),
        migrations.AddField(
            model_name='additionalfield',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='add_field_created_by', to='workflow.ActivityUser', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='additionalfield',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='add_field_modified_by', to='workflow.ActivityUser', verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='activitytable',
            name='country',
            field=models.ManyToManyField(blank=True, to='activity.Country'),
        ),
        migrations.AddField(
            model_name='activitytable',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.ActivityUser'),
        ),
    ]
