# Generated by Django 2.2.3 on 2019-07-05 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0001_initial'),
        ('activity', '0002_auto_20190705_0204'),
        ('formlibrary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingattendance',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.WorkflowLevel1'),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='project_agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.WorkflowLevel2', verbose_name='Project Initiation'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='initiation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.WorkflowLevel2', verbose_name='Project Initiation'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='office_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.Office'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.WorkflowLevel1'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Province'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='distribution',
            field=models.ManyToManyField(blank=True, to='formlibrary.Distribution'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='program',
            field=models.ManyToManyField(blank=True, to='workflow.WorkflowLevel1'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.Location'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='training',
            field=models.ManyToManyField(blank=True, to='formlibrary.TrainingAttendance'),
        ),
    ]
