# Generated by Django 2.2.3 on 2019-07-05 09:04

import activity.models
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_1', models.CharField(blank=True, max_length=100, verbose_name='Administrative IndicatorLevel 1')),
                ('level_2', models.CharField(blank=True, max_length=100, verbose_name='Administrative IndicatorLevel 2')),
                ('level_3', models.CharField(blank=True, max_length=100, verbose_name='Administrative IndicatorLevel 3')),
                ('level_4', models.CharField(blank=True, max_length=100, verbose_name='Administrative IndicatorLevel 4')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='Create Date')),
                ('modified_date', models.DateTimeField(blank=True, null=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name_plural': 'Administrative Levels',
                'ordering': ('level_1',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('singular_label', models.CharField(default='Contact', max_length=100, verbose_name='Singular Label')),
                ('plural_label', models.CharField(default='Contacts', max_length=100, verbose_name='Plural Label')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Phone Number')),
                ('street', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('zip_code', models.CharField(blank=True, max_length=25, verbose_name='Zip/Postal Code')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State/Province')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='Create Date')),
                ('modified_date', models.DateTimeField(blank=True, null=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name_plural': 'Contacts',
                'ordering': ('first_name',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='Country Name')),
                ('code', models.CharField(blank=True, max_length=4, verbose_name='2 Letter Country Code')),
                ('description', models.TextField(blank=True, max_length=765, verbose_name='Description/Notes')),
                ('latitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='Longitude')),
                ('zoom', models.IntegerField(default=5, verbose_name='Zoom')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('edit_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ('country',),
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Currency UUID')),
                ('name', models.CharField(max_length=255, verbose_name='Currency Name')),
                ('symbol', models.CharField(blank=True, max_length=10, verbose_name='Currency Symbol')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Currency Code')),
                ('create_date', models.DateTimeField(editable=False, null=True, verbose_name='Create Date')),
                ('modified_date', models.DateTimeField(editable=False, null=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Location UUID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Site Name')),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=100, verbose_name='Location Status')),
                ('latitude', models.DecimalField(decimal_places=16, default=Decimal('0.00'), max_digits=25, verbose_name='Latitude Coordinates')),
                ('longitude', models.DecimalField(decimal_places=16, default=Decimal('0.00'), max_digits=25, verbose_name='Longitude Coordinates')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='Create Date')),
                ('modified_date', models.DateTimeField(blank=True, null=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name_plural': 'Sites',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Organization Sub-Type UUID')),
                ('type', models.CharField(max_length=100, unique=True, verbose_name='Location Type')),
                ('create_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Create Date')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Edit Date')),
            ],
            options={
                'verbose_name_plural': 'Location Types',
                'ordering': ('create_date',),
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Office Name')),
                ('code', models.CharField(blank=True, max_length=255, verbose_name='Office Code')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='Create Date')),
                ('modified_date', models.DateTimeField(blank=True, null=True, verbose_name='Modified Date')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='First Organization', max_length=135, verbose_name='Full Organization Name')),
                ('short_name', models.CharField(max_length=100, verbose_name='Organization Short Name')),
                ('url', models.CharField(blank=True, max_length=165, verbose_name='Organization Website url')),
                ('description', models.TextField(blank=True, max_length=765, null=True, verbose_name='Description/Notes')),
                ('link_to_description_relationship', models.CharField(blank=True, max_length=165, verbose_name='Link to Description of Relationship')),
                ('link_to_due_diligence', models.CharField(blank=True, max_length=165, verbose_name='Link to Due Diligence')),
                ('singular_label', models.CharField(blank=True, default='Organization', max_length=135, verbose_name='Organization Singular Label')),
                ('plural_label', models.CharField(blank=True, default='Organizations', max_length=135, verbose_name='Organization Plural Label')),
                ('organization_identifier', models.CharField(blank=True, max_length=100, verbose_name='Organization Identifier')),
                ('organization_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=100, verbose_name='Organization Status')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='Create Date')),
                ('modified_date', models.DateTimeField(blank=True, null=True, verbose_name='Modified Date')),
                ('theme_color', models.CharField(default='25ced1', max_length=6, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 6', regex='^.{6}$')], verbose_name='Organization Costum Color')),
                ('logo', models.ImageField(blank=True, help_text='Image of minimum 2000 width and 500 height, maximum of 100 ko', upload_to='images/', validators=[activity.models.validate_image], verbose_name='Your Organization logo')),
            ],
            options={
                'verbose_name_plural': 'Organizations',
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Organization Sub-Type UUID')),
                ('sub_type', models.CharField(max_length=100, unique=True, verbose_name='Organization Sub-Type')),
                ('create_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Create Date')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Edit Date')),
            ],
            options={
                'verbose_name_plural': 'Organization Sub Types',
                'ordering': ('create_date',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Organization Type UUID')),
                ('type', models.CharField(max_length=100, unique=True, verbose_name='Organization Type')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='Create Date')),
                ('modified_date', models.DateTimeField(blank=True, null=True, verbose_name='Edit Date')),
            ],
            options={
                'verbose_name_plural': 'Organization Types',
                'ordering': ('create_date',),
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Portfolio UUID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Portfolio Name')),
                ('create_date', models.DateTimeField(editable=False, null=True, verbose_name='Create Date')),
                ('modified_date', models.DateTimeField(editable=False, null=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name_plural': 'Portfolios',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=255, verbose_name='Sector Name')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='Create Date')),
                ('modified_date', models.DateTimeField(blank=True, null=True, verbose_name='Modified Date')),
            ],
            options={
                'verbose_name_plural': 'Location',
                'ordering': ('sector',),
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Workspace UUID')),
                ('name', models.CharField(max_length=36, verbose_name='Workspace Name')),
                ('url', models.CharField(blank=True, max_length=100, verbose_name='Workspace Url')),
                ('description', models.TextField(blank=True, max_length=765, verbose_name='Workspace Description')),
                ('workflow_level_1', models.CharField(default='Project', max_length=36)),
                ('workflow_level_2', models.CharField(default='Activity', max_length=36)),
                ('workflow_level_3', models.CharField(default='Sub-Activity', max_length=36)),
                ('workflow_level_4', models.CharField(default='Task', max_length=36)),
                ('organization_label', models.CharField(default='Organization', max_length=36)),
                ('indicator_label', models.CharField(default='Indicator', max_length=36)),
                ('form_label', models.CharField(default='Forms', max_length=36)),
                ('site_label', models.CharField(default='Sites', max_length=36)),
                ('create_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Create Date')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Edit Date')),
            ],
            options={
                'verbose_name_plural': 'Workspaces',
                'ordering': ('name',),
            },
        ),
    ]
