# Generated by Django 2.2.3 on 2019-07-05 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_created_by', to='workflow.ActivityUser', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_modified_by', to='workflow.ActivityUser', verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='sector',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sector_created_by', to='workflow.ActivityUser', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='sector',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sector_modified_by', to='workflow.ActivityUser', verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='sector',
            name='parent_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_sectors', to='activity.Sector'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_created_by', to='workflow.ActivityUser', verbose_name='Created Vy'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_modified_by', to='workflow.ActivityUser', verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Workspace'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_type_created_by', to='workflow.ActivityUser', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='organizationtype',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_type_modified_by', to='workflow.ActivityUser', verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='organizationsubtype',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_sub_created_by', to='workflow.ActivityUser', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='organizationsubtype',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_sub_modified_by', to='workflow.ActivityUser', verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='organizationsubtype',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.OrganizationType', verbose_name='Organization Type'),
        ),
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_created_by', to='workflow.ActivityUser', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='organization',
            name='documentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Documentation'),
        ),
        migrations.AddField(
            model_name='organization',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_modified_by', to='workflow.ActivityUser', verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.OrganizationType'),
        ),
        migrations.AddField(
            model_name='organization',
            name='parent_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='activity.Organization'),
        ),
        migrations.AddField(
            model_name='office',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_created_by', to='workflow.ActivityUser', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='office',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_modified_by', to='workflow.ActivityUser', verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='locationtype',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_type_created_by', to='workflow.ActivityUser', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='locationtype',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_type_modified_by', to='workflow.ActivityUser', verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='location',
            name='admin_levels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.AdministrativeLevel', verbose_name='Administrative Levels'),
        ),
        migrations.AddField(
            model_name='location',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.Contact', verbose_name='Location Contact'),
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Country', verbose_name='Country of Location'),
        ),
        migrations.AddField(
            model_name='location',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_created_by', to='workflow.ActivityUser', verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='location',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_modified_by', to='workflow.ActivityUser', verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='location',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.Office', verbose_name='Location Office'),
        ),
        migrations.AddField(
            model_name='location',
            name='parent_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_locations', to='activity.Location'),
        ),
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.LocationType', verbose_name='Location Type'),
        ),
        migrations.AddField(
            model_name='currency',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_created_by', to='workflow.ActivityUser', verbose_name='Created Vy'),
        ),
        migrations.AddField(
            model_name='currency',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_modified_by', to='workflow.ActivityUser', verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='country',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.Workspace'),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_created_by', to='workflow.ActivityUser', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='contact',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_modified_by', to='workflow.ActivityUser', verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Organization', verbose_name='Organization Contact'),
        ),
        migrations.AddField(
            model_name='administrativelevel',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_level_created_by', to='workflow.ActivityUser', verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='administrativelevel',
            name='modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_level_modified_by', to='workflow.ActivityUser', verbose_name='Modified By'),
        ),
    ]
