# Generated by Django 2.2 on 2019-05-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='level_3_label',
            field=models.CharField(blank=True, default='Activity', max_length=255, verbose_name='Project/Program Organization Level 3 label'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='level_4_label',
            field=models.CharField(blank=True, default='Component', max_length=255, verbose_name='Project/Program Organization Level 4 label'),
        ),
    ]
